CREATE TABLE `HUB_GEO` (
  `SQN` int(11) NOT NULL AUTO_INCREMENT,
  `GEO_BEZIRKNUMBER` int(11) NOT NULL,
  `GEO_LOAD_DATE` datetime NOT NULL,
  `GEO_REC_SOURCE` varchar(45) NOT NULL,
  PRIMARY KEY (`SQN`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;

CREATE TABLE `HUB_KND` (
  `SQN` int(11) NOT NULL AUTO_INCREMENT,
  `KND_NUMBER` int(11) NOT NULL,
  `KND_LOAD_DATE` datetime NOT NULL,
  `KND_REC_SOURCE` varchar(45) NOT NULL,
  PRIMARY KEY (`SQN`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=latin1;

CREATE TABLE `HUB_KTO` (
  `SQN` int(11) NOT NULL AUTO_INCREMENT,
  `KTO_NUMBER` int(11) NOT NULL,
  `KTO_LOAD_DATE` datetime NOT NULL,
  `KTO_REC_SOURCE` varchar(45) NOT NULL,
  PRIMARY KEY (`SQN`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=latin1;

CREATE TABLE `HUB_PRT` (
  `SQN` int(11) NOT NULL AUTO_INCREMENT,
  `PRT_NUMBER` int(11) NOT NULL,
  `PRT_LOAD_DATE` datetime NOT NULL,
  `PRT_REC_SOURCE` varchar(45) NOT NULL,
  PRIMARY KEY (`SQN`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

CREATE TABLE `HUB_UMS_ART` (
  `SQN` int(11) NOT NULL AUTO_INCREMENT,
  `UMS_ART_NUMBER` int(11) NOT NULL,
  `UMS_LOAD_DATE` datetime NOT NULL,
  `UMS_REC_SOURCE` varchar(45) NOT NULL,
  PRIMARY KEY (`SQN`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;

CREATE TABLE `LINK_KND_GEO` (
  `SQN` int(11) NOT NULL AUTO_INCREMENT,
  `HUB_KND_SQN` int(11) NOT NULL,
  `HUB_GEO_SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime DEFAULT NULL,
  `REC_SOURCE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SQN`),
  KEY `fk_LINK_UMS_HUB_KND_idx` (`HUB_KND_SQN`),
  KEY `fk_LINK_UMS_HUB_GEO_idx` (`HUB_GEO_SQN`),
  CONSTRAINT `fk_LINK_KND_GEO_HUB_GEO` FOREIGN KEY (`HUB_GEO_SQN`) REFERENCES `HUB_GEO` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINK_KND_GEO_HUB_KND` FOREIGN KEY (`HUB_KND_SQN`) REFERENCES `HUB_KND` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `LINK_KTO_KND` (
  `SQN` int(11) NOT NULL AUTO_INCREMENT,
  `HUB_KTO_SQN` int(11) NOT NULL,
  `HUB_KND_SQN` int(11) DEFAULT NULL,
  `HUB_PRT_SQN` int(11) DEFAULT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  PRIMARY KEY (`SQN`),
  KEY `fk_HUB_KND_has_HUB_PRT_HUB_KND1_idx` (`HUB_KTO_SQN`),
  KEY `fk_LINK_KND_PRT_HUB_KND1_idx` (`HUB_KND_SQN`),
  KEY `fk_LINK_KTO_KND_HUB_PRT1_idx` (`HUB_PRT_SQN`),
  CONSTRAINT `fk_HUB_KND_has_HUB_PRT_HUB_KND1` FOREIGN KEY (`HUB_KTO_SQN`) REFERENCES `HUB_KTO` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINK_KND_PRT_HUB_KND` FOREIGN KEY (`HUB_KND_SQN`) REFERENCES `HUB_KND` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINK_KTO_KND_HUB_PRT` FOREIGN KEY (`HUB_PRT_SQN`) REFERENCES `HUB_PRT` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `HAL_LINK_GEO` (
  `SQN` int(11) NOT NULL AUTO_INCREMENT,
  `HUB_GEO_SQN` int(11) NOT NULL,
  `HUB_GEO_PARENT_SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  PRIMARY KEY (`SQN`),
  KEY `fk_LINK_KND_PRT_HUB_GEO_idx` (`HUB_GEO_SQN`),
  KEY `fk_LINK_KND_PRT_HUB_GEO_PAR_idx` (`HUB_GEO_PARENT_SQN`),
  CONSTRAINT `fk_LINK_GEO_HUB_GEO` FOREIGN KEY (`HUB_GEO_SQN`) REFERENCES `HUB_GEO` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINK_GEO_HUB_GEP_PARENT` FOREIGN KEY (`HUB_GEO_PARENT_SQN`) REFERENCES `HUB_GEO` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;


CREATE TABLE `TA_LINK_UMS` (
  `SQN` int(11) NOT NULL AUTO_INCREMENT,
  `HUB_KTO_SQN` int(11) NOT NULL,
  `HUB_UMS_ART_SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  PRIMARY KEY (`SQN`),
  KEY `fk_TA_LINK_UMS_HUB_UMS_idx` (`HUB_UMS_ART_SQN`),
  KEY `fk_TA_LINK_UMS_HUB_KTO1_idx` (`HUB_KTO_SQN`),
  CONSTRAINT `fk_LINK_UMS_HUB_KTO` FOREIGN KEY (`HUB_KTO_SQN`) REFERENCES `HUB_KTO` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_LINK_UMS_HUB_UMS_ART` FOREIGN KEY (`HUB_UMS_ART_SQN`) REFERENCES `HUB_UMS_ART` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=latin1;


CREATE TABLE `SAT_GEO` (
  `SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `LOAD_END_DATE` datetime DEFAULT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  `BEZ_GEB_REGION` varchar(100) DEFAULT NULL,
  `SPARKASSE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SQN`,`LOAD_DATE`),
  KEY `fk_SAT_GEO_HUB_GEO1_idx` (`SQN`),
  CONSTRAINT `fk_SAT_GEO_HUB_GEO` FOREIGN KEY (`SQN`) REFERENCES `HUB_GEO` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SAT_KND` (
  `SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `LOAD_END_DATE` datetime DEFAULT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  `FAMILIENSTAND` tinyint(4) DEFAULT NULL,
  `GESCHLECHT` tinyint(1) DEFAULT NULL,
  `NACHNAME` varchar(100) DEFAULT NULL,
  `VORNAME` varchar(100) DEFAULT NULL,
  `BERUF` tinyint(4) DEFAULT NULL,
  `GEBURTSDATUM` date DEFAULT NULL,
  `VERSTORBEN` tinyint(1) DEFAULT NULL,
  `SPARKASSE` varchar(45) DEFAULT NULL,
  `WERBUNGSVERBOT` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`SQN`,`LOAD_DATE`),
  KEY `fk_SAT_KND_copy1_HUB_KTO1_idx` (`SQN`),
  CONSTRAINT `fk_SAT_KND_copy1_HUB_KTO10` FOREIGN KEY (`SQN`) REFERENCES `HUB_KND` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SAT_KND_ADDRESS` (
  `SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `LOAD_END_DATE` datetime DEFAULT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  `STRASSE` varchar(100) DEFAULT NULL,
  `HAUSNUMMER` varchar(45) DEFAULT NULL,
  `POSTLEITZAHL` varchar(45) DEFAULT NULL,
  `ORT` varchar(100) DEFAULT NULL,
  `LAND` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`SQN`,`LOAD_DATE`),
  KEY `fk_SAT_KND_copy1_HUB_KTO1_idx` (`SQN`),
  CONSTRAINT `fk_SAT_KND_copy1_HUB_KTO1` FOREIGN KEY (`SQN`) REFERENCES `HUB_KND` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SAT_KTO` (
  `SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `LOAD_END_DATE` datetime DEFAULT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  `TARIF` varchar(45) DEFAULT NULL,
  `SPARZIEL` decimal(10,2) DEFAULT NULL,
  `EINRICHTUNGSSPARKASSE` varchar(45) DEFAULT NULL,
  `LEBEND` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`SQN`,`LOAD_DATE`),
  KEY `fk_SAT_KTO_idx` (`SQN`),
  CONSTRAINT `fk_SAT_KTO_HUB_KTO` FOREIGN KEY (`SQN`) REFERENCES `HUB_KTO` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SAT_KTO_BESTAND` (
  `SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `LOAD_END_DATE` datetime DEFAULT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  `F_KONTOSTAND` decimal(10,2) DEFAULT NULL,
  `F_BEWERTUNGSZAHL` decimal(5,2) DEFAULT NULL,
  PRIMARY KEY (`SQN`,`LOAD_DATE`),
  KEY `fk_SAT_KTO_BESTAND_idx` (`SQN`),
  CONSTRAINT `fk_SAT_KTO_BESTAND_HUB_KTO` FOREIGN KEY (`SQN`) REFERENCES `HUB_KTO` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SAT_PRT` (
  `SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `LOAD_END_DATE` datetime DEFAULT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  `PARTNER_1` varchar(45) DEFAULT NULL,
  `PARTNER_2` varchar(45) DEFAULT NULL,
  `KUNDENTYP` char(1) DEFAULT NULL,
  PRIMARY KEY (`SQN`,`LOAD_DATE`),
  KEY `fk_SAT_PRT_HUB_PRT1_idx` (`SQN`),
  CONSTRAINT `fk_SAT_PRT_HUB_PRT1` FOREIGN KEY (`SQN`) REFERENCES `HUB_PRT` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SAT_UMS` (
  `SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  `SOLL_HABEN` char(1) DEFAULT NULL,
  `UMSATZBETRAG` decimal(10,2) DEFAULT NULL,
  `STORNO` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`SQN`,`LOAD_DATE`),
  KEY `fk_SAT_UMS_LINK_UMS1_idx` (`SQN`),
  CONSTRAINT `fk_SAT_UMS_LINK_UMS1` FOREIGN KEY (`SQN`) REFERENCES `TA_LINK_UMS` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SAT_UMS_ART` (
  `SQN` int(11) NOT NULL,
  `LOAD_DATE` datetime NOT NULL,
  `LOAD_END_DATE` datetime DEFAULT NULL,
  `REC_SOURCE` varchar(45) NOT NULL,
  `NAME` varchar(45) DEFAULT NULL,
  `GRUPPENNAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`SQN`,`LOAD_DATE`),
  KEY `fk_SAT_UMS_ART_HUB_UMS_ART_idx` (`SQN`),
  CONSTRAINT `fk_SAT_UMS_ART_HUB_UMS_ART` FOREIGN KEY (`SQN`) REFERENCES `HUB_UMS_ART` (`SQN`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
